[package]
name = "trans_rights_bot"
version = "0.2.0"
authors = ["Tom Panton <pantonshire@gmail.com>"]
edition = "2018"

[dependencies]
goldcrest = { git = "https://github.com/Pantonshire/goldcrest" }
tokio = { version = "1.0", features = ["full"] }
chrono = "0.4"
rand = "0.8"
